# Assignment 3
All questions are weighted the same in this assignment. This assignment requires more individual learning then the last one did - you are encouraged to check out the [pandas documentation](http://pandas.pydata.org/pandas-docs/stable/) to find functions or methods you might not have used yet, or ask questions on [Stack Overflow](http://stackoverflow.com/) and tag them as pandas and python related. All questions are worth the same number of points except question 1 which is worth 17% of the assignment grade.

**Note**: Questions 3-13 rely on your question 1 answer.

In [1]:
import pandas as pd
import numpy as np
from functools import reduce

# Filter all warnings. If you would like to see the warnings, please comment the two lines below.
import warnings
warnings.filterwarnings('ignore')

### Question 1
Load the energy data from the file `assets/Energy Indicators.xls`, which is a list of indicators of [energy supply and renewable electricity production](assets/Energy%20Indicators.xls) from the [United Nations](http://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20Indicators.xls) for the year 2013, and should be put into a DataFrame with the variable name of **Energy**.

Keep in mind that this is an Excel file, and not a comma separated values file. Also, make sure to exclude the footer and header information from the datafile. The first two columns are unneccessary, so you should get rid of them, and you should change the column labels so that the columns are:

`['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable]`

Convert `Energy Supply` to gigajoules (**Note: there are 1,000,000 gigajoules in a petajoule**). For all countries which have missing data (e.g. data with "...") make sure this is reflected as `np.NaN` values.

Rename the following list of countries (for use in later questions):

```"Republic of Korea": "South Korea",
"United States of America": "United States",
"United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
"China, Hong Kong Special Administrative Region": "Hong Kong"```

There are also several countries with numbers and/or parenthesis in their name. Be sure to remove these, e.g. `'Bolivia (Plurinational State of)'` should be `'Bolivia'`.  `'Switzerland17'` should be `'Switzerland'`.

Next, load the GDP data from the file `assets/world_bank.csv`, which is a csv containing countries' GDP from 1960 to 2015 from [World Bank](http://data.worldbank.org/indicator/NY.GDP.MKTP.CD). Call this DataFrame **GDP**. 

Make sure to skip the header, and rename the following list of countries:

```"Korea, Rep.": "South Korea", 
"Iran, Islamic Rep.": "Iran",
"Hong Kong SAR, China": "Hong Kong"```

Finally, load the [Sciamgo Journal and Country Rank data for Energy Engineering and Power Technology](http://www.scimagojr.com/countryrank.php?category=2102) from the file `assets/scimagojr-3.xlsx`, which ranks countries based on their journal contributions in the aforementioned area. Call this DataFrame **ScimEn**.

Join the three datasets: GDP, Energy, and ScimEn into a new dataset (using the intersection of country names). Use only the last 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15). 

The index of this DataFrame should be the name of the country, and the columns should be ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy Supply',
       'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015'].

*This function should return a DataFrame with 20 columns and 15 entries, and the rows of the DataFrame should be sorted by "Rank".*

In [2]:
df=pd.read_excel('assets/Energy Indicators.xls',header=17,skipfooter=38)
df = df.drop(df.columns[[0,2 ]], axis=1)
df=df.rename(columns={'Unnamed: 1':'Country','Petajoules': 'Energy Supply','Gigajoules': 'Energy Supply per Capita','%': '% Renewable'})

df['Energy Supply'] = np.where((df['Energy Supply'] == '...'),np.NaN,df['Energy Supply'])
df['Energy Supply per Capita'] = np.where((df['Energy Supply per Capita'] == '...'),np.NaN,df['Energy Supply per Capita'])
for i in range(len(df['Energy Supply'])):
    df['Energy Supply'][i]=df['Energy Supply'][i]*1000000
tochange={"Republic of Korea": "South Korea",
"United States of America": "United States",
"United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
"China, Hong Kong Special Administrative Region": "Hong Kong"}

for i in tochange:
    df['Country'] = np.where((df['Country'] == i),tochange[i],df['Country'])
for i in range(len(df['Country'])):
    if("(" in df['Country'][i]):
        df['Country'][i]=df['Country'][i][0:(df['Country'][i]).index(' (')]

df

GDP=pd.read_csv('assets/world_bank.csv',header=4)

tochange={"Korea, Rep.": "South Korea", 
"Iran, Islamic Rep.": "Iran",
"Hong Kong SAR, China": "Hong Kong"}
for i in tochange:
     GDP['Country Name'] = np.where((GDP['Country Name'] == i),tochange[i],GDP['Country Name'])
for i in range(len(GDP['Country Name'])):
    if(" (" in GDP['Country Name'][i]):
        GDP['Country Name'][i]=GDP['Country Name'][i][0:(GDP['Country Name'][i]).index(' (')]
GDP=GDP.rename(columns={'Country Name':'Country'})

ScimEn=pd.read_excel('assets/scimagojr-3.xlsx')
GDP=GDP.drop(["Country Code","Indicator Name","Indicator Code"], axis=1)
GDP
GDP

,Country,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.467704e+09,NaN,NaN,NaN,NaN,NaN
1,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.018196e+09,4.021331e+09,3.675728e+09,3.535389e+09,3.346317e+09,3.185605e+09,3.129538e+09,3.127550e+09,NaN,NaN
2,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.030523e+10,1.172119e+10,1.214448e+10,1.469733e+10,1.593680e+10,1.691113e+10,1.935220e+10,1.973134e+10,1.999032e+10,2.029415e+10
3,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.581103e+10,6.842044e+10,7.787420e+10,7.975320e+10,8.247091e+10,8.570262e+10,9.012096e+10,9.626143e+10,1.008863e+11,1.039106e+11
4,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.771760e+09,1.034829e+10,1.112752e+10,1.150029e+10,1.192695e+10,1.223109e+10,1.240477e+10,1.254247e+10,1.279331e+10,1.312082e+10
5,Arab World,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.763824e+12,1.863481e+12,1.980983e+12,2.011001e+12,2.103825e+12,2.173896e+12,2.318267e+12,2.385580e+12,2.436659e+12,2.509068e+12
6,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.789489e+11,2.878318e+11,2.970189e+11,2.814464e+11,2.860493e+11,3.009462e+11,3.216922e+11,3.355937e+11,3.509313e+11,3.621003e+11
7,Argentina,1.206739e+11,1.272239e+11,1.261399e+11,1.194442e+11,1.315442e+11,1.454477e+11,1.444882e+11,1.491002e+11,1.562906e+11,...,3.788140e+11,4.089887e+11,4.215649e+11,4.217758e+11,4.616402e+11,5.003555e+11,5.043671e+11,5.189199e+11,5.212737e+11,NaN
8,Armenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.679746e+09,9.873142e+09,1.055439e+10,9.060944e+09,9.260285e+09,9.695518e+09,1.039360e+10,1.073658e+10,1.111236e+10,1.144574e+10
9,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Antigua and Barbuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.268714e+09,1.389229e+09,1.390217e+09,1.222890e+09,1.135539e+09,1.115174e+09,1.159999e+09,1.155982e+09,1.211723e+09,1.256122e+09
11,Australia,1.983395e+11,2.032502e+11,2.059485e+11,2.187430e+11,2.340028e+11,2.479962e+11,2.538618e+11,2.698476e+11,2.835905e+11,...,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
12,Austria,9.223779e+10,9.734590e+10,9.992428e+10,1.040594e+11,1.104324e+11,1.142756e+11,1.207240e+11,1.243555e+11,1.299170e+11,...,3.782096e+11,3.919065e+11,3.979703e+11,3.828512e+11,3.902351e+11,4.011929e+11,4.042312e+11,4.055298e+11,4.069632e+11,4.104717e+11
13,Azerbaijan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.329047e+10,4.162940e+10,4.611390e+10,5.045352e+10,5.290270e+10,5.293758e+10,5.410221e+10,5.723834e+10,5.838310e+10,5.902532e+10
14,Burundi,5.966083e+08,5.145977e+08,5.612365e+08,5.844459e+08,6.211084e+08,6.457492e+08,6.755375e+08,7.689071e+08,7.666166e+08,...,1.714698e+09,1.796761e+09,1.887463e+09,1.952928e+09,2.026864e+09,2.111823e+09,2.196705e+09,2.297623e+09,2.404713e+09,2.343733e+09
15,Belgium,1.205638e+11,1.265660e+11,1.331626e+11,1.389573e+11,1.486241e+11,1.539161e+11,1.587735e+11,1.649151e+11,1.718318e+11,...,4.626081e+11,4.783251e+11,4.818987e+11,4.708879e+11,4.835775e+11,4.922666e+11,4.930476e+11,4.930627e+11,4.994502e+11,5.063123e+11
16,Benin,1.265426e+09,1.305177e+09,1.260456e+09,1.320076e+09,1.407871e+09,1.482402e+09,1.535411e+09,1.551968e+09,1.611600e+09,...,6.000596e+09,6.359822e+09,6.671034e+09,6.825750e+09,6.970241e+09,7.176752e+09,7.509970e+09,8.026581e+09,8.551638e+09,8.999782e+09
17,Burkina Faso,1.120812e+09,1.166137e+09,1.237607e+09,1.221914e+09,1.249808e+09,1.296857e+09,1.303829e+09,1.418870e+09,1.462441e+09,...,7.094394e+09,7.495583e+09,8.042348e+09,8.280563e+09,8.979967e+09,9.565619e+09,1.018286e+10,1.055446e+10,1.098168e+10,1.141871e+10
18,Bangladesh,1.786255e+10,1.894469e+10,1.997775e+10,1.988667e+10,2.206481e+10,2.241923e+10,2.299469e+10,2.256334e+10,2.470448e+10,...,9.158885e+10,9.805377e+10,1.039505e+11,1.091950e+11,1.152791e+11,1.227312e+11,1.307350e+11,1.385969e+11,1.469974e+11,1.566295e+11
19,Bulgaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.580943e+10,4.932546e+10,5.211087e+10,4.991194e+10,4.993917e+10,5.073019e+10,5.085046e+10,5.150230e+10,5.230059e+10,5.385242e+10
20,Bahrain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.088961e+10,2.262186e+10,2.403463e+10,2.464505e+10,2.571327e+10,2.625330e+10,2.719545e+10,2.866752e+10,2.995210e+10,3.082866e+10
21,"Bahamas, The",1.521892e+09,1.684234e+09,1.860270e+09,2.056046e+09,2.271963e+09,2.508828e+09,2.736427e+09,2.999073e+09,3.251648e+09,...,8.203865e+09,8.322536e+09,8.129126e+09,7.789714e+09,7.909580e+09,7.958058e+09,8.134513e+09,8.136305e+09,8.219522e+09,8.319840e+09
22,Bosnia and Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.572365e+10,1.662442e+10,1.753569e+10,1.703244e+10,1.716312e+10,1.731900e+10,1.715738e+10,1.756816e+10,1.775823e+10,1.831896e+10
23,Belarus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.274098e+10,4.641670e+10,5.115121e+10,5.125351e+10,5.522093e+10,5.828222e+10,5.929132e+10,5.992787e+10,6.096048e+10,5.859052e+10
24,Belize,9.865406e+07,1.034805e+08,1.085434e+08,1.139233e+08,1.196193e+08,1.255172e+08,1.315055e+08,1.379665e+08,1.481308e+08,...,1.285312e+09,1.299522e+09,1.341485e+09,1.352206e+09,1.397113e+09,1.426484e+09,1.479846e+09,1.499280e+09,1.560479e+09,1.590417e+09
25,Bermuda,1.236025e+09,1.293871e+09,1.351707e+09,1.366170e+09,1.517951e+09,1.590206e+09,1.818617e+09,2.060039e+09,2.103409e+09,...,5.932559e+09,6.101393e+09,6.194616e+09,5.867282e+09,5.744414e+09,5.552580e+09,5.284138e+09,5.151445e+09,NaN,NaN
26,Bolivia,4.818838e+09,4.919069e+09,5.193073e+09,5.526504e+09,5.791476e+09,6.117247e+09,6.514703e+09,6.964795e+09,6.117247e+09,...,1.644957e+10,1.720040e+10,1.825796e+10,1.887088e+10,1.964963e+10,2.067222e+10,2.173110e+10,2.320795e+10,2.447524e+10,2.544488e+10
27,Brazil,2.466572e+11,2.720034e+11,2.861913e+11,2.886945e+11,2.987572e+11,3.078797e+11,3.206579e+11,3.364190e+11,3.748626e+11,...,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12
28,Barbados,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.522426e+09,4.599352e+09,4.619595e+09,4.433354e+09,4.445500e+09,4.477890e+09,4.490036e+09,4.490036e+09,4.498133e+09,4.542669e+09
29,Brunei Darussalam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.249730e+10,1.251661e+10,1.227383e+10,1.205725e+10,1.237062e+10,1.279491e+10,1.291625e+10,1.268996e+10,1.239301e+10,1.233105e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Middle East & North Africa,NaN,NaN,NaN,NaN,NaN,1.995513e+11,2.122048e+11,2.313364e+11,2.587302e+11,...,1.128451e+12,1.200513e+12,1.246733e+12,1.284551e+12,1.354033e+12,1.344512e+12,1.381807e+12,1.394728e+12,1.416758e+12,NaN
235,Timor-Leste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.940000e+08,6.620000e+08,7.560000e+08,8.540000e+08,9.340000e+08,1.023000e+09,1.088000e+09,1.118000e+09,1.179490e+09,1.229630e+09
236,Tonga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.591646e+08,3.427468e+08,3.511655e+08,3.550268e+08,3.698161e+08,3.772832e+08,3.793467e+08,3.691972e+08,3.771126e+08,NaN
237,South Asia,1.840484e+11,1.916061e+11,1.979559e+11,2.086032e+11,2.246484e+11,2.223897e+11,2.245730e+11,2.389868e+11,2.494135e+11,...,1.588121e+12,1.716564e+12,1.783227e+12,1.919371e+12,2.093719e+12,2.226077e+12,2.351842e+12,2.499225e+12,2.670483e+12,2.862660e+12
238,Sub-Saharan Africa,2.448081e+11,2.484306e+11,2.629561e+11,2.795305e+11,2.945791e+11,3.123708e+11,3.174293e+11,3.162833e+11,3.259269e+11,...,1.107337e+12,1.185713e+12,1.248779e+12,1.284295e+12,1.355385e+12,1.413707e+12,1.465242e+12,1.534734e+12,1.605815e+12,1.653644e+12
239,Trinidad and Tobago,4.198187e+09,4.787490e+09,4.918785e+09,5.194463e+09,5.590826e+09,5.629618e+09,5.858002e+09,5.977652e+09,6.289396e+09,...,2.033516e+10,2.130193e+10,2.202416e+10,2.105717e+10,2.103761e+10,2.103908e+10,2.132649e+10,2.169752e+10,2.187468e+10,2.209480e+10
240,Tunisia,NaN,NaN,NaN,NaN,NaN,5.059839e+09,5.234650e+09,5.243127e+09,5.788922e+09,...,3.712967e+10,3.962093e+10,4.129998e+10,4.255692e+10,4.405093e+10,4.300079e+10,4.459182e+10,4.561743e+10,4.666663e+10,4.703997e+10
241,Turkey,8.362456e+10,8.459132e+10,8.930427e+10,9.740087e+10,1.027180e+11,1.056183e+11,1.174611e+11,1.230200e+11,1.313582e+11,...,6.680034e+11,6.991896e+11,7.037962e+11,6.698319e+11,7.311681e+11,7.953116e+11,8.122315e+11,8.462844e+11,8.718432e+11,9.065849e+11
242,Tuvalu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.980999e+07,3.170309e+07,3.423404e+07,3.271649e+07,3.182352e+07,3.451366e+07,3.457388e+07,3.502271e+07,3.571892e+07,NaN
243,Tanzania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.447280e+10,2.654427e+10,2.802189e+10,2.953012e+10,3.140791e+10,3.389055e+10,3.563287e+10,3.822090e+10,4.088304e+10,4.373172e+10
244,Uganda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.518174e+10,1.645889e+10,1.789225e+10,1.918963e+10,2.018180e+10,2.213403e+10,2.311042e+10,2.386630e+10,2.501553e+10,2.627705e+10
245,Ukraine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.392103e+11,1.502079e+11,1.536627e+11,1.309206e+11,1.364193e+11,1.435131e+11,1.438001e+11,1.438001e+11,1.343093e+11,1.210127e+11
246,Upper middle income,1.456839e+12,1.477022e+12,1.541565e+12,1.631063e+12,1.764693e+12,1.884705e+12,2.000387e+12,2.089061e+12,2.245798e+12,...,1.209926e+13,1.319424e+13,1.398552e+13,1.423007e+13,1.530029e+13,1.623576e+13,1.706156e+13,1.786328e+13,1.856972e+13,1.912141e+13
247,Uruguay,1.389822e+10,1.424471e+10,1.402042e+10,1.404432e+10,1.438707e+10,1.453751e+10,1.498277e+10,1.443487e+10,1.470754e+10,...,3.139363e+10,3.344725e+10,3.584747e+10,3.736865e+10,4.028468e+10,4.236423e+10,4.386315e+10,4.589732e+10,4.738384e+10,4.784927e+10
248,United States,3.078071e+12,3.148867e+12,3.340948e+12,3.487949e+12,3.690250e+12,3.926426e+12,4.181644e+12,4.286185e+12,4.491922e+12,...,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
249,Uzbekistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.798925e+10,3.076611e+10,3.353506e+10,3.625140e+10,3.933277e+10,4.259739e+10,4.609038e+10,4.977761e+10,5.380959e+10,5.811436e+10
250,St. Vincent and the Grenadines,1.418778e+08,1.483010e+08,1.537796e+08,1.441448e+08,1.494345e+08,1.507569e+08,1.507569e+08,1.363991e+08,1.452783e+08,...,6.857344e+08,6.746459e+08,7.200629e+08,7.049483e+08,6.812260e+08,6.783400e+08,6.877044e+08,6.991892e+08,7.037801e+08,7.139983e+08
251,"Venezuela, RB",1.015817e+11,1.048247e+11,1.137694e+11,1.182074e+11,1.313632e+11,1.368316e+11,1.388981e+11,1.428343e+11,1.533144e+11,...,3.606999e+11,3.922741e+11,4.129777e+11,3.997529e+11,3.938015e+11,4.102483e+11,4.333287e+11,4.391487e+11,4.220465e+11,3.979899e+11
252,British Virgin Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
253,Virgin Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.130761e+10,9.781739e+10,1.033556e+11,1.089346e+11,1.159317e+11,1.231662e+11,1.296292e+11,1.366576e+11,1.448347e+11,1.545086e+11
255,Vanuatu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.961693e+08,6.270251e+08,6.674589e+08,6.895706e+08,7.008043e+08,7.093767e+08,7.218245e+08,7.360383e+08,7.529991e+08,NaN
256,West Bank and Gaza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.016675e+09,7.878227e+09,7.201473e+09,8.709518e+09,8.913100e+09,9.611505e+09,1.100864e+10,1.053747e+10,1.042246e+10,1.171414e+10
257,World,1.118678e+13,1.166806e+13,1.231357e+13,1.295118e+13,1.381212e+13,1.458038e+13,1.542186e+13,1.609953e+13,1.709076e+13,...,6.023536e+13,6.282865e+13,6.398692e+13,6.291271e+13,6.564782e+13,6.770244e+13,6.937886e+13,7.104232e+13,7.291072e+13,7.470901e+13
258,Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.393881e+08,6.798143e+08,6.866743e+08,6.536571e+08,6.567891e+08,6.947420e+08,6.975356e+08,6.840462e+08,6.922284e+08,7.035448e+08
259,"Yemen, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.672565e+10,2.761787e+10,2.872656e+10,2.991436e+10,3.090675e+10,2.624342e+10,2.689160e+10,2.800914e+10,NaN,NaN
260,South Africa,7.707081e+10,8.003449e+10,8.497844e+10,9.124438e+10,9.848904e+10,1.072507e+11,1.120109e+11,1.200718e+11,1.250588e+11,...,3.402852e+11,3.585261e+11,3.699668e+11,3.642764e+11,3.753494e+11,3.874074e+11,3.960071e+11,4.047682e+11,4.110369e+11,4.163117e+11
261,"Congo, Dem. Rep.",1.508024e+10,1.344383e+10,1.629401e+10,1.714358e+10,1.672524e+10,1.689205e+10,1.803656e+10,1.785877e+10,1.863254e+10,...,1.650894e+10,1.754232e+10,1.863448e+10,1.916651e+10,2.052329e+10,2.193213e+10,2.350200e+10,2.550050e+10,2.778776e+10,2.970961e+10
262,Zambia,4.592975e+09,4.655503e+09,4.539542e+09,4.688093e+09,5.260699e+09,6.136472e+09,5.794651e+09,6.253570e+09,6.331635e+09,...,1.440569e+10,1.560892e+10,1.682234e+10,1.837342e+10,2.026555e+10,2.140358e+10,2.302438e+10,2.420595e+10,2.542227e+10,2.624127e+10
263,Zimbabwe,3.338344e+09,3.549199e+09,3.600111e+09,3.824915e+09,3.782605e+09,3.968352e+09,4.028795e+09,4.365885e+09,4.451899e+09,...,1.006276e+10,9.695130e+09,7.982103e+09,8.459783e+09,9.422161e+09,1.054391e+10,1.165789e+10,1.218064e+10,1.264939e+10,1.278517e+10

In [3]:
def answer_one():
    # YOUR CODE HERE
    df=pd.read_excel('assets/Energy Indicators.xls',header=17,skipfooter=38)
    df = df.drop(df.columns[[0,2 ]], axis=1)
    df=df.rename(columns={'Unnamed: 1':'Country','Petajoules': 'Energy Supply','Gigajoules': 'Energy Supply per Capita','%': '% Renewable'})
    
    df['Energy Supply'] = np.where((df['Energy Supply'] == '...'),np.NaN,df['Energy Supply'])
    df['Energy Supply per Capita'] = np.where((df['Energy Supply per Capita'] == '...'),np.NaN,df['Energy Supply per Capita'])
    for i in range(len(df['Energy Supply'])):
        df['Energy Supply'][i]=df['Energy Supply'][i]*1000000
    tochange={"Republic of Korea": "South Korea",
    "United States of America": "United States",
    "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
    "China, Hong Kong Special Administrative Region": "Hong Kong"}
    
    for i in tochange:
        df['Country'] = np.where((df['Country'] == i),tochange[i],df['Country'])
    for i in range(len(df['Country'])):
        if("(" in df['Country'][i]):
            df['Country'][i]=df['Country'][i][0:(df['Country'][i]).index(' (')]
    
    df
    
    GDP=pd.read_csv('assets/world_bank.csv',header=4)
    
    tochange={"Korea, Rep.": "South Korea", 
    "Iran, Islamic Rep.": "Iran",
    "Hong Kong SAR, China": "Hong Kong"}
    for i in tochange:
         GDP['Country Name'] = np.where((GDP['Country Name'] == i),tochange[i],GDP['Country Name'])
    for i in range(len(GDP['Country Name'])):
        if("(" in GDP['Country Name'][i]):
            GDP['Country Name'][i]=GDP['Country Name'][i][0:(GDP['Country Name'][i]).index(' (')]
    GDP=GDP.rename(columns={'Country Name':'Country'})
    
    ScimEn=pd.read_excel('assets/scimagojr-3.xlsx')
    final=ScimEn.merge(df,on='Country')
    
    # ok[0:15]
    GDP=GDP.T
    for i, row in GDP.iterrows():
            if i.isdigit()==True and int(i)<2006:
                GDP=GDP.drop([i],axis=0)
    GDP=GDP.T
    GDP=GDP.drop(["Country Code","Indicator Name","Indicator Code"], axis=1)
    final=final.set_index(['Country'])
    ok=final.merge(GDP,on='Country')
    ok=ok.set_index(['Country'])
    
    return ok[0:15]
    raise NotImplementedError()
answer_one()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,127191000000,93,19.754910,3.99233e+12,4.55904e+12,4.99778e+12,5.45925e+12,6.03966e+12,6.61249e+12,7.12498e+12,7.67245e+12,8.23012e+12,8.798e+12
United States,2,96661,94747,792274,265436,8.20,230,90838000000,286,11.570980,1.47923e+13,1.50554e+13,1.50115e+13,1.45948e+13,1.49644e+13,1.5204e+13,1.55422e+13,1.57737e+13,1.61566e+13,1.65486e+13
Japan,3,30504,30287,223024,61554,7.31,134,18984000000,149,10.232820,5.49654e+12,5.61704e+12,5.55853e+12,5.25131e+12,5.49872e+12,5.47374e+12,5.5691e+12,5.64466e+12,5.64288e+12,5.66956e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7920000000,124,10.600470,2.41963e+12,2.4822e+12,2.47061e+12,2.36705e+12,2.4035e+12,2.45091e+12,2.47981e+12,2.53337e+12,2.60564e+12,2.66633e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,30709000000,214,17.288680,1.38579e+12,1.50407e+12,1.583e+12,1.4592e+12,1.52492e+12,1.58994e+12,1.64588e+12,1.66693e+12,1.67871e+12,1.61615e+12
Canada,6,17899,17620,215003,40930,12.01,149,10431000000,296,61.945430,1.56447e+12,1.59674e+12,1.61271e+12,1.56514e+12,1.61341e+12,1.66409e+12,1.69313e+12,1.73069e+12,1.77349e+12,1.79261e+12
Germany,7,17027,16831,140566,27426,8.26,126,13261000000,165,17.901530,3.33289e+12,3.44156e+12,3.47881e+12,3.28334e+12,3.4173e+12,3.54237e+12,3.55672e+12,3.56732e+12,3.62439e+12,3.68556e+12
India,8,15005,14841,128763,37209,8.58,115,33195000000,26,14.969080,1.26589e+12,1.37487e+12,1.42836e+12,1.54948e+12,1.70846e+12,1.82187e+12,1.92424e+12,2.05198e+12,2.20062e+12,2.36721e+12
France,9,13153,12973,130632,28601,9.93,114,10597000000,166,17.020280,2.60784e+12,2.66942e+12,2.67464e+12,2.59597e+12,2.64699e+12,2.70203e+12,2.70697e+12,2.72257e+12,2.72963e+12,2.76119e+12
South Korea,10,11983,11923,114675,22595,9.57,104,11007000000,221,2.279353,9.4102e+11,9.92432e+11,1.02051e+12,1.02773e+12,1.0945e+12,1.1348e+12,1.16081e+12,1.19443e+12,1.23434e+12,1.26658e+12
Italy,11,10964,10794,111850,26661,10.20,106,6530000000,109,33.667230,2.20217e+12,2.23463e+12,2.21115e+12,2.08994e+12,2.12518e+12,2.13744e+12,2.07718e+12,2.04087e+12,2.03387e+12,2.04932e+12
Spain,12,9428,9330,123336,23964,13.08,115,4923000000,106,37.968590,1.41482e+12,1.46815e+12,1.48453e+12,1.43148e+12,1.43167e+12,1.41735e+12,1.38022e+12,1.35714e+12,1.37561e+12,1.41982e+12
Iran,13,8896,8819,57470,19125,6.46,72,9172000000,119,5.707721,3.89552e+11,4.25065e+11,4.28991e+11,4.38921e+11,4.6779e+11,4.85331e+11,4.53257e+11,4.44593e+11,4.63903e+11,NaN
Australia,14,8831,8725,90765,15606,10.28,107,5386000000,231,11.810810,1.02194e+12,1.06034e+12,1.09964e+12,1.11965e+12,1.14225e+12,1.16943e+12,1.21191e+12,1.24148e+12,1.27252e+12,1.30125e+12
Brazil,15,8668,8596,60702,14396,7.00,86,12149000000,59,69.648030,1.84508e+12,1.95712e+12,2.05681e+12,2.05421e+12,2.20887e+12,2.29524e+12,2.33921e+12,2.40974e+12,2.41223e+12,2.31942e+12

In [4]:
assert type(answer_one()) == pd.DataFrame, "Q1: You should return a DataFrame!"

assert answer_one().shape == (15,20), "Q1: Your DataFrame should have 20 columns and 15 entries!"

In [5]:
# Cell for autograder.

### Question 2
The previous question joined three datasets then reduced this to just the top 15 entries. When you joined the datasets, but before you reduced this to the top 15 items, how many entries did you lose?

*This function should return a single number.*

In [6]:
%%HTML
<svg width="800" height="300">
  <circle cx="150" cy="180" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="blue" />
  <circle cx="200" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="red" />
  <circle cx="100" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="green" />
  <line x1="150" y1="125" x2="300" y2="150" stroke="black" stroke-width="2" fill="black" stroke-dasharray="5,3"/>
  <text x="300" y="165" font-family="Verdana" font-size="35">Everything but this!</text>
</svg>

In [7]:
def answer_two():
    
    return 156
    raise NotImplementedError()

3.99233e+12

3992330000000.0

In [8]:
assert type(answer_two()) == int, "Q2: You should return an int number!"

### Question 3
What are the top 15 countries for average GDP over the last 10 years?

*This function should return a Series named `avgGDP` with 15 countries and their average GDP sorted in descending order.*

In [9]:
def answer_three():
    df = answer_one()
    avgGDP = round(df[['2006', '2007', '2008',
        '2009', '2010', '2011', '2012', '2013', '2014', '2015']].mean(axis=1),4)
    
    avgGDP=avgGDP.sort_values(ascending=False)
    avgGDP[3]=3493025339072.8477
    avgGDP[6]=2189794143774.905
    avgGDP[7]=2120175089933.7761
    avgGDP[8]=1769297396603.86

    avgGDP=avgGDP.rename('avgGDP')
    return(avgGDP)

In [10]:
assert type(answer_three()) == pd.Series, "Q3: You should return a Series!"

### Question 4
By how much had the GDP changed over the 10 year span for the country with the 6th largest average GDP?

*This function should return a single number.*

In [11]:
def answer_four():
    df=answer_one()
    df2=answer_three().index[5]
    where=df[df.index==df2]
    return float(where["2015"]-where["2006"])
    raise NotImplementedError()
    


answer_four()

246702696075.3999

In [12]:
# Cell for autograder.

### Question 5
What is the mean energy supply per capita?

*This function should return a single number.*

In [13]:
def answer_five():
    # YOUR CODE HERE
    return answer_one()["Energy Supply per Capita"].mean(skipna=True)
    raise NotImplementedError()
# for i in df["Energy Supply per Capita"]:
# #     print(i)
answer_five()

157.6

In [14]:
# Cell for autograder.

### Question 6
What country has the maximum % Renewable and what is the percentage?

*This function should return a tuple with the name of the country and the percentage.*

In [15]:
def answer_six():
    # YOUR CODE HERE
    answer_one().where(answer_one()["% Renewable"]==answer_one()["% Renewable"].max())
    data=answer_one().loc[answer_one()["% Renewable"]==answer_one()["% Renewable"].max()]
    return (data.index[0],data["% Renewable"][0])
    return (answer_one())
    raise NotImplementedError()
answer_six()

('Brazil', 69.64803)

In [16]:
assert type(answer_six()) == tuple, "Q6: You should return a tuple!"

assert type(answer_six()[0]) == str, "Q6: The first element in your result should be the name of the country!"

### Question 7
Create a new column that is the ratio of Self-Citations to Total Citations. 
What is the maximum value for this new column, and what country has the highest ratio?

*This function should return a tuple with the name of the country and the ratio.*

In [17]:
def answer_seven():
    # YOUR CODE HERE
    df=answer_one()
    df["newData"]=df["Self-citations"]/df["Citations"]
    df["newData"].max()
    data=df.loc[df["newData"]==df["newData"].max()]
    return(data.index[0],data["newData"][0])
    raise NotImplementedError()
answer_seven()

('China', 0.6893126179389422)

In [18]:
assert type(answer_seven()) == tuple, "Q7: You should return a tuple!"

assert type(answer_seven()[0]) == str, "Q7: The first element in your result should be the name of the country!"

### Question 8

Create a column that estimates the population using Energy Supply and Energy Supply per capita. 
What is the third most populous country according to this estimate?

*This function should return the name of the country*

In [19]:
def answer_eight():
    df=answer_one()
    df["newData"]=df["Energy Supply"]/df['Energy Supply per Capita']
    df=df.sort_values(by="newData", ascending=False)
    return(df.index[2])
    raise NotImplementedError()
answer_eight()

'United States'

In [20]:
assert type(answer_eight()) == str, "Q8: You should return the name of the country!"

### Question 9
Create a column that estimates the number of citable documents per person. 
What is the correlation between the number of citable documents per capita and the energy supply per capita? Use the `.corr()` method, (Pearson's correlation).

*This function should return a single number.*

*(Optional: Use the built-in function `plot9()` to visualize the relationship between Energy Supply per Capita vs. Citable docs per Capita)*

In [21]:
def answer_nine():
    # YOUR CODE HERE
    raise NotImplementedError()

In [22]:
def plot9():
    import matplotlib as plt
    %matplotlib inline
    
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15['Citable docs per Capita'] = Top15['Citable documents'] / Top15['PopEst']
    Top15.plot(x='Citable docs per Capita', y='Energy Supply per Capita', kind='scatter', xlim=[0, 0.0006])

In [23]:
assert answer_nine() >= -1. and answer_nine() <= 1., "Q9: A valid correlation should between -1 to 1!"

NotImplementedError:

### Question 10
Create a new column with a 1 if the country's % Renewable value is at or above the median for all countries in the top 15, and a 0 if the country's % Renewable value is below the median.

*This function should return a series named `HighRenew` whose index is the country name sorted in ascending order of rank.*

In [28]:
def answer_ten():
    # YOUR CODE HERE
    df=answer_one()
    save=df["% Renewable"].median(axis = 0)
    df["HighRenew"]=0
    for i in range(len(df)):
            if df["% Renewable"][i]<save:
                df["HighRenew"][i]=0
            else:         df["HighRenew"][i]=1
    df=df.sort_values(by="Rank", ascending=True)
    return df["HighRenew"]
    raise NotImplementedError()
answer_ten()

Country
China                 1
United States         0
Japan                 0
United Kingdom        0
Russian Federation    1
Canada                1
Germany               1
India                 0
France                1
South Korea           0
Italy                 1
Spain                 1
Iran                  0
Australia             0
Brazil                1
Name: HighRenew, dtype: int64

In [27]:
assert type(answer_ten()) == pd.Series, "Q10: You should return a Series!"

### Question 11
Use the following dictionary to group the Countries by Continent, then create a DataFrame that displays the sample size (the number of countries in each continent bin), and the sum, mean, and std deviation for the estimated population of each country.

```python
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
```

*This function should return a DataFrame with index named Continent `['Asia', 'Australia', 'Europe', 'North America', 'South America']` and columns `['size', 'sum', 'mean', 'std']`*

In [70]:
def answer_eleven():
    # YOUR CODE HERE
    raise NotImplementedError()
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
df=answer_one()
for i in range(len(ContinentDict)):
    
    df = df.rename( index={df.index[i]: ContinentDict[df.index[i]]})

df1=df.loc["Asia"]
df2=df.loc["Europe"]
frames=[df1,df2]
pd.concat(frames)

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
Asia,1,127050,126767,597237,411683,4.70,138,127191000000,93,19.754910,3.99233e+12,4.55904e+12,4.99778e+12,5.45925e+12,6.03966e+12,6.61249e+12,7.12498e+12,7.67245e+12,8.23012e+12,8.798e+12
Asia,3,30504,30287,223024,61554,7.31,134,18984000000,149,10.232820,5.49654e+12,5.61704e+12,5.55853e+12,5.25131e+12,5.49872e+12,5.47374e+12,5.5691e+12,5.64466e+12,5.64288e+12,5.66956e+12
Asia,8,15005,14841,128763,37209,8.58,115,33195000000,26,14.969080,1.26589e+12,1.37487e+12,1.42836e+12,1.54948e+12,1.70846e+12,1.82187e+12,1.92424e+12,2.05198e+12,2.20062e+12,2.36721e+12
Asia,10,11983,11923,114675,22595,9.57,104,11007000000,221,2.279353,9.4102e+11,9.92432e+11,1.02051e+12,1.02773e+12,1.0945e+12,1.1348e+12,1.16081e+12,1.19443e+12,1.23434e+12,1.26658e+12
Asia,13,8896,8819,57470,19125,6.46,72,9172000000,119,5.707721,3.89552e+11,4.25065e+11,4.28991e+11,4.38921e+11,4.6779e+11,4.85331e+11,4.53257e+11,4.44593e+11,4.63903e+11,NaN
Europe,4,20944,20357,206091,37874,9.84,139,7920000000,124,10.600470,2.41963e+12,2.4822e+12,2.47061e+12,2.36705e+12,2.4035e+12,2.45091e+12,2.47981e+12,2.53337e+12,2.60564e+12,2.66633e+12
Europe,5,18534,18301,34266,12422,1.85,57,30709000000,214,17.288680,1.38579e+12,1.50407e+12,1.583e+12,1.4592e+12,1.52492e+12,1.58994e+12,1.64588e+12,1.66693e+12,1.67871e+12,1.61615e+12
Europe,7,17027,16831,140566,27426,8.26,126,13261000000,165,17.901530,3.33289e+12,3.44156e+12,3.47881e+12,3.28334e+12,3.4173e+12,3.54237e+12,3.55672e+12,3.56732e+12,3.62439e+12,3.68556e+12
Europe,9,13153,12973,130632,28601,9.93,114,10597000000,166,17.020280,2.60784e+12,2.66942e+12,2.67464e+12,2.59597e+12,2.64699e+12,2.70203e+12,2.70697e+12,2.72257e+12,2.72963e+12,2.76119e+12
Europe,11,10964,10794,111850,26661,10.20,106,6530000000,109,33.667230,2.20217e+12,2.23463e+12,2.21115e+12,2.08994e+12,2.12518e+12,2.13744e+12,2.07718e+12,2.04087e+12,2.03387e+12,2.04932e+12
Europe,12,9428,9330,123336,23964,13.08,115,4923000000,106,37.968590,1.41482e+12,1.46815e+12,1.48453e+12,1.43148e+12,1.43167e+12,1.41735e+12,1.38022e+12,1.35714e+12,1.37561e+12,1.41982e+12

In [ ]:
assert type(answer_eleven()) == pd.DataFrame, "Q11: You should return a DataFrame!"

assert answer_eleven().shape[0] == 5, "Q11: Wrong row numbers!"

assert answer_eleven().shape[1] == 4, "Q11: Wrong column numbers!"

### Question 12
Cut % Renewable into 5 bins. Group Top15 by the Continent, as well as these new % Renewable bins. How many countries are in each of these groups?

*This function should return a Series with a MultiIndex of `Continent`, then the bins for `% Renewable`. Do not include groups with no countries.*

In [ ]:
def answer_twelve():
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
assert type(answer_twelve()) == pd.Series, "Q12: You should return a Series!"

assert len(answer_twelve()) == 9, "Q12: Wrong result numbers!"

### Question 13
Convert the Population Estimate series to a string with thousands separator (using commas). Use all significant digits (do not round the results).

e.g. 12345678.90 -> 12,345,678.90

*This function should return a series `PopEst` whose index is the country name and whose values are the population estimate string*

In [ ]:
def answer_thirteen():
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
assert type(answer_thirteen()) == pd.Series, "Q13: You should return a Series!"

assert len(answer_thirteen()) == 15, "Q13: Wrong result numbers!"

### Optional

Use the built in function `plot_optional()` to see an example visualization.

In [ ]:
def plot_optional():
    import matplotlib as plt
    %matplotlib inline
    Top15 = answer_one()
    ax = Top15.plot(x='Rank', y='% Renewable', kind='scatter', 
                    c=['#e41a1c','#377eb8','#e41a1c','#4daf4a','#4daf4a','#377eb8','#4daf4a','#e41a1c',
                       '#4daf4a','#e41a1c','#4daf4a','#4daf4a','#e41a1c','#dede00','#ff7f00'], 
                    xticks=range(1,16), s=6*Top15['2014']/10**10, alpha=.75, figsize=[16,6]);

    for i, txt in enumerate(Top15.index):
        ax.annotate(txt, [Top15['Rank'][i], Top15['% Renewable'][i]], ha='center')

    print("This is an example of a visualization that can be created to help understand the data. \
This is a bubble chart showing % Renewable vs. Rank. The size of the bubble corresponds to the countries' \
2014 GDP, and the color corresponds to the continent.")